import type { AppSyncResolverHandler } from 'aws-lambda';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, QueryCommand, GetCommand } from '@aws-sdk/lib-dynamodb';
import Anthropic from '@anthropic-ai/sdk';
import { requireHousehold, callerHouseholdIds } from '../requireHousehold';
import { logEvent, logWarning, logFailure, tokenUsage } from '../telemetry';

const ddbClient = DynamoDBDocumentClient.from(new DynamoDBClient({}));

const MAPPING_TABLE = process.env.MAPPING_TABLE_NAME!;
const HOUSEHOLD_STORE_TABLE = process.env.HOUSEHOLD_STORE_TABLE_NAME!;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY!;

/**
 * Haiku, measured rather than assumed.
 *
 * The swap was held back for a year of caution: placing a product in a store's
 * own aisles is the app's one piece of judgement, and a worse guess costs a
 * person a walk across a shop — quietly, with no error to notice. So it was
 * decided by running both models over 105 products against Stop&Shop's real
 * layout (`scripts/aisle-bakeoff`), scored against the store's own directory
 * where the directory names the product.
 *
 * On that objective subset Sonnet placed 30 of 31 and Haiku 28, for a third of
 * the cost. Haiku's two misses were a verbatim directory line it reasoned past,
 * which `applyDirectory` now settles without a model, and one product it
 * declined to place rather than guess at — which surfaces as an unmapped item,
 * and is the better failure of the two.
 *
 * Re-run the bake-off before changing this line, and do it in the same pass as
 * the Bedrock migration, which rewrites it.
 */
const MODEL = 'claude-haiku-4-5';

// Amplify Gen2 GSI generated by `index('storeId')` on the ProductAisleMapping model
// (see amplify/data/resource.ts). Partition key: storeId, no sort key.
const MAPPING_BY_STORE_INDEX = 'productAisleMappingsByStoreId';

interface Arguments {
  storeId: string;
  productName?: string;      // Single mode (existing) - optional when using batch
  normalizedName?: string;   // Optional when using batch
  productId?: string;
  products?: Array<{         // Batch mode (new)
    productName: string;
    normalizedName: string;
    productId?: string;
  }>;
}

interface Response {
  success: boolean;
  suggestedAisle?: string;   // Single mode
  confidence?: number;
  reasoning?: string;
  error?: string;
  results?: Array<{          // Batch mode (new)
    productName: string;
    normalizedName: string;
    productId?: string;
    suggestedAisle: string;
    confidence: number;
    reasoning: string;
  }>;
}

export interface ExistingMapping {
  aisleId: string;
  normalizedName?: string;
  productId?: string;
  confidence?: number;
  /// Kept only so a directory line can be told from a guess; never shown to the
  /// model, which sees `buildMappingContext`'s summary instead.
  reasoning?: string;
}


/**
 * Fetch existing mappings for a store to use as context
 */
export interface StoreAisle {
  id: string;
  number?: string;
  name?: string;
  description?: string;
  displayOrder?: number;
}

/// The aisles the store itself declares. This is what inference should be
/// matching against: every store is seeded with seven standard departments
/// carrying descriptions written for exactly this purpose ("Milk, cream,
/// yogurt, butter, cheese, eggs..."). Building context only from products
/// already mapped meant those descriptions were never seen, and a store could
/// only ever place items into aisles that already had something in them.
async function fetchStoreAisles(storeId: string, callerHouseholds: string[]): Promise<StoreAisle[]> {
  try {
    const result = await ddbClient.send(
      new GetCommand({
        TableName: HOUSEHOLD_STORE_TABLE,
        Key: { id: storeId },
        ProjectionExpression: 'aisleLayout, householdId',
      })
    );

    // `requireHousehold` proves the caller is in *a* household. It says nothing
    // about *this* store, and `storeId` arrives as an argument — so without this,
    // a member of one household could read another household's aisle layout, and
    // the mappings below it, which are a list of what those people buy. Needs the
    // store's UUID to be worth anything, but "needs a UUID" is not access control.
    //
    // The store is fetched here anyway, so the check costs nothing.
    const owner = result.Item?.householdId;
    if (owner && !callerHouseholds.includes(owner)) {
      logWarning('auth.rejected', { reason: 'store_not_in_caller_household' });
      throw new Error('That store belongs to a different household.');
    }

    const layout = result.Item?.aisleLayout;
    if (!layout) return [];
    const parsed = typeof layout === 'string' ? JSON.parse(layout) : layout;
    return Array.isArray(parsed) ? (parsed as StoreAisle[]) : [];
  } catch (err) {
    // An ownership rejection is not a read failure and must not be turned into
    // an empty layout, which would let the request carry on regardless.
    if (err instanceof Error && err.message.startsWith('That store belongs')) throw err;
    logFailure('ai.infer.storeReadFailed', err);
    return [];
  }
}

async function fetchExistingMappings(storeId: string): Promise<ExistingMapping[]> {
  const mappings: ExistingMapping[] = [];
  let lastEvaluatedKey: Record<string, any> | undefined;

  // Query the storeId GSI so cost/latency scale with this store's mappings only
  do {
    const result = await ddbClient.send(
      new QueryCommand({
        TableName: MAPPING_TABLE,
        IndexName: MAPPING_BY_STORE_INDEX,
        KeyConditionExpression: 'storeId = :storeId',
        ExpressionAttributeValues: {
          ':storeId': storeId,
        },
        ProjectionExpression: 'aisleId, userAisleOverride, normalizedName, productId, confidence, reasoning',
        ExclusiveStartKey: lastEvaluatedKey,
      })
    );

    if (result.Items) {
      mappings.push(
        ...result.Items.map((item) => ({
          // What a person said beats what a model guessed. The app resolves
          // `userAisleOverride ?? aisleId` on read, and the model has to learn
          // from the same answer the shopper sees — otherwise a sighting made in
          // the shop teaches inference nothing, and if `aisleId` ever drifts the
          // two diverge silently.
          aisleId: (item.userAisleOverride ?? item.aisleId) as string,
          normalizedName: item.normalizedName as string | undefined,
          productId: item.productId as string | undefined,
          // A sighting is not a guess with a confidence score. Dropping the
          // model's old score stops a stale 0.4 arguing with something seen.
          confidence: item.userAisleOverride ? undefined : (item.confidence as number | undefined),
          // A row a person moved is no longer the directory's claim, whatever
          // its reasoning still says, so the directory backstop must not see it.
          reasoning: item.userAisleOverride ? undefined : (item.reasoning as string | undefined),
        }))
      );
    }

    lastEvaluatedKey = result.LastEvaluatedKey;
  } while (lastEvaluatedKey);

  return mappings;
}

/**
 * The built-in departments, mirroring `StoreService.namedDepartments` in Swift.
 *
 * Needed here because the model answers in free text and echoes whatever form it
 * was shown. A shop with no scanned aisles has no declared layout at all, so the
 * only context is the existing mappings — and once one of those says "Produce"
 * while another says "standard-produce", the model perpetuates both and the same
 * aisle appears twice on screen with its items split between them.
 *
 * Canonicalising on the way in stops that at the source rather than papering over
 * it at render time.
 */
/**
 * The seven places every shop has, whatever its size.
 *
 * These are departments — somewhere you walk to, with a sign over it. They are
 * not categories. "Condiments & Sauces" was in this list for a while and is not
 * a place: in a real shop it is *in* aisle 5, and offering it as a section told
 * people to walk somewhere that does not exist. A store has named departments
 * and numbered aisles; there is no third kind.
 */
const STANDARD_SECTIONS: Array<{ id: string; name: string }> = [
  { id: 'standard-produce',    name: 'Produce' },
  { id: 'standard-bakery',     name: 'Bakery' },
  { id: 'standard-deli',       name: 'Deli' },
  { id: 'standard-seafood',    name: 'Seafood' },
  { id: 'standard-meat',       name: 'Meat & Poultry' },
  { id: 'standard-dairy',      name: 'Dairy & Eggs' },
  { id: 'standard-frozen',     name: 'Frozen' },
];

/**
 * One id per place, whatever form the answer arrived in.
 *
 * Resolution order matches AisleNaming on the client: the store's own declared
 * layout first, since that is the only source that knows this shop; then the
 * built-in departments by id or name; then the value untouched, because an aisle
 * we cannot place is better kept than mangled.
 */
export function canonicalAisleId(value: string, aisles: StoreAisle[] = []): string {
  const trimmed = (value ?? '').trim();
  if (!trimmed) return trimmed;
  const key = trimmed.toLowerCase();

  // "Use null if nothing fits" is the right answer and the model gives it — but
  // the schema types `aisle` as a string, so it arrives as the four characters
  // n-u-l-l rather than a JSON null, sails through `r.aisle || 'Unknown'`, and
  // the review screen prints "null" next to Flour in confident green. An
  // unplaced item is unplaced; say so with an empty id, which every caller
  // already treats as "No aisle yet".
  if (key === 'null' || key === 'none' || key === 'undefined' || key === 'n/a') return '';

  const declared = aisles.find(
    (a) =>
      a.id?.toLowerCase() === key ||
      a.name?.trim().toLowerCase() === key ||
      a.number?.trim().toLowerCase() === key
  );
  if (declared?.id) return declared.id;

  const standard = STANDARD_SECTIONS.find(
    (sec) => sec.id === key || sec.name.toLowerCase() === key
  );
  if (standard) return standard.id;

  return trimmed;
}

/**
 * Build aisle context from existing mappings
 * Groups products by aisle for the LLM to understand store layout
 */
export function buildAisleContext(mappings: ExistingMapping[], aisles: StoreAisle[] = []): string {
  // Collapse the historical spellings before the model ever sees them.
  mappings = mappings.map((m) => ({ ...m, aisleId: canonicalAisleId(m.aisleId, aisles) }));
  const declared: string[] = [];
  if (aisles.length > 0) {
    declared.push('Aisles and departments in this store:');
    const sorted = [...aisles].sort((a, b) => (a.displayOrder ?? 0) - (b.displayOrder ?? 0));
    for (const aisle of sorted) {
      const label = [aisle.number, aisle.name].filter(Boolean).join(' ').trim() || aisle.id;
      declared.push(aisle.description ? `- ${label} (id: ${aisle.id}) — ${aisle.description}` : `- ${label} (id: ${aisle.id})`);
    }
    declared.push('');
    if (mappings.length > 0) declared.push('Products already placed:');
  }
  const prefix = declared.join('\n');
  return prefix + buildMappingContext(mappings);
}

export function buildMappingContext(mappings: ExistingMapping[]): string {
  // Group by aisle
  const aisleGroups: Record<string, string[]> = {};

  for (const mapping of mappings) {
    const aisle = mapping.aisleId;
    // Deliberately not falling back to productId. A UUID teaches the model
    // nothing about what lives in an aisle, and it costs input tokens on every
    // call to say so. Rows written before the client sent normalizedName are
    // skipped rather than shown as hex.
    const name = mapping.normalizedName?.trim();
    if (!name) continue;

    if (!aisleGroups[aisle]) {
      aisleGroups[aisle] = [];
    }
    aisleGroups[aisle].push(name);
  }

  // Format as readable context
  const lines: string[] = [];
  const sortedAisles = Object.keys(aisleGroups).sort((a, b) => {
    const numA = parseInt(a);
    const numB = parseInt(b);
    if (!isNaN(numA) && !isNaN(numB)) return numA - numB;
    if (!isNaN(numA)) return -1;
    if (!isNaN(numB)) return 1;
    return a.localeCompare(b);
  });

  for (const aisle of sortedAisles) {
    const products = aisleGroups[aisle];
    // Limit to 20 products per aisle to keep context manageable
    const displayProducts = products.slice(0, 20);
    const moreCount = products.length - displayProducts.length;

    let line = `Aisle ${aisle}: ${displayProducts.join(', ')}`;
    if (moreCount > 0) {
      line += ` (+${moreCount} more)`;
    }
    lines.push(line);
  }

  return lines.join('\n');
}

/**
 * Call Claude to infer the best aisle for a product
 */
async function inferAisle(
  productName: string,
  aisleContext: string,
  anthropic: Anthropic
): Promise<{ aisle: string; confidence: number; reasoning: string; usage: Anthropic.Usage }> {
  const prompt = `You are helping a shopper find where a product is located in a grocery store.

STORE AISLE LAYOUT (based on existing product mappings):
${aisleContext}

PRODUCT TO LOCATE: "${productName}"

Based on the store's existing aisle layout above, determine which aisle this product is most likely in.

Think about:
1. What category is this product? (produce, dairy, meat, canned goods, spices, etc.)
2. Which aisle has similar products?
3. If it's a fresh herb like dill/basil, it's likely in Produce
4. If it's a spice/dried herb, it's likely with spices

Respond with ONLY a JSON object (no other text):
{
  "aisle": "the exact id shown in parentheses above, e.g. standard-produce. Never invent one. Use null if nothing fits.",
  "confidence": 0.0 to 1.0,
  "reasoning": "at most 10 words, no full sentence, e.g. \"aisle 4 already has pasta\""
}

Confidence guidelines:
- 0.9-1.0: Very confident (many similar products in that aisle)
- 0.7-0.89: Confident (clear category match)
- 0.5-0.69: Moderate (reasonable guess based on category)
- 0.3-0.49: Low confidence (weak match)
- <0.3: Very uncertain`;

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 4096,
    temperature: 0,
    messages: [
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  const textContent = response.content.find((block) => block.type === 'text');
  if (!textContent || textContent.type !== 'text') {
    throw new Error('No text response from Claude');
  }

  // Parse JSON response
  const jsonMatch = textContent.text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('Invalid response format from Claude');
  }

  const result = JSON.parse(jsonMatch[0]);

  // Post-processing: Clean up aisle value to remove redundant "Aisle" prefix
  let aisleValue = result.aisle || 'Unknown';
  const aisleMatch = aisleValue.match(/^aisle\s+(.+)$/i);
  if (aisleMatch) {
    const originalAisle = aisleValue;
    aisleValue = aisleMatch[1].trim();
    logWarning('ai.infer.aislePrefixStripped', { chars: originalAisle.length });
  }

  return {
    aisle: aisleValue,
    confidence: typeof result.confidence === 'number' ? result.confidence : 0.5,
    reasoning: result.reasoning || 'No reasoning provided',
    usage: response.usage,
  };
}

/**
 * Call Claude to infer aisles for multiple products at once (batch mode)
 */
export async function inferAisleBatch(
  products: Array<{ productName: string; normalizedName: string; productId?: string }>,
  aisleContext: string,
  anthropic: Anthropic,
  // Only ever passed by scripts/aisle-bakeoff, which runs this same prompt
  // against two models to compare placements. Production takes the default.
  model: string = MODEL
): Promise<{
  results: Array<{ productName: string; aisle: string; confidence: number; reasoning: string }>;
  usage: Anthropic.Usage;
}> {
  // Build numbered list of products
  const productList = products.map((p, i) => `${i + 1}. "${p.productName}"`).join('\n');

  const prompt = `You are helping a shopper find where products are located in a grocery store.

STORE AISLE LAYOUT (based on existing product mappings):
${aisleContext}

PRODUCTS TO LOCATE:
${productList}

For EACH product, determine which aisle it is most likely in based on the store layout above.

Respond with ONLY a JSON array (no other text):
[
  {"productName": "exact product name", "aisle": "the exact id shown in parentheses above, e.g. standard-produce. Never invent one. Use null if nothing fits.", "confidence": 0.0 to 1.0, "reasoning": "at most 10 words, no full sentence"},
  ...
]

Confidence guidelines:
- 0.9-1.0: Very confident (many similar products in that aisle)
- 0.7-0.89: Confident (clear category match)
- 0.5-0.69: Moderate (reasonable guess)
- <0.5: Low confidence`;

  const response = await anthropic.messages.create({
    model,
    max_tokens: 8192,  // Larger for batch
    temperature: 0,
    messages: [{ role: 'user', content: prompt }],
  });

  // Parse array response
  const textContent = response.content.find((block) => block.type === 'text');
  if (!textContent || textContent.type !== 'text') {
    throw new Error('No text response from Claude');
  }

  const jsonMatch = textContent.text.match(/\[[\s\S]*\]/);
  if (!jsonMatch) {
    throw new Error('Invalid response format from Claude');
  }

  const results = JSON.parse(jsonMatch[0]);

  // Post-process to clean up aisle values (same as single mode)
  const cleaned = results.map((r: any) => {
    let aisleValue = r.aisle || 'Unknown';
    const aisleMatch = aisleValue.match(/^aisle\s+(.+)$/i);
    if (aisleMatch) {
      aisleValue = aisleMatch[1].trim();
    }
    return {
      productName: r.productName,
      aisle: aisleValue,
      confidence: typeof r.confidence === 'number' ? r.confidence : 0.5,
      reasoning: r.reasoning || 'No reasoning provided',
    };
  });

  return { results: cleaned, usage: response.usage };
}

/**
 * What the store's own directory says, keyed by the name it was read under.
 *
 * A row is only ground truth when its reasoning is a verbatim directory line
 * and the stored name still matches what was read. `source: IMAGE` alone is not
 * enough — rows like `frozen pizza -> Frozen` carry that source with a reasoning
 * of "belongs in frozen section", which is a guess wearing the label.
 */
function signPlacements(mappings: ExistingMapping[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const row of mappings) {
    const quoted = /^Directly listed on store sign: "(.+?)"$/.exec((row.reasoning ?? '').trim());
    if (!quoted) continue;
    const name = (row.normalizedName ?? '').trim().toLowerCase();
    if (name && quoted[1].trim().toLowerCase() === name) out.set(name, row.aisleId);
  }
  return out;
}

/**
 * Replace a guess with the directory where the directory names the product.
 *
 * This should never fire. Both callers already drop items that have a mapping
 * before they ask, so a product the directory names outright does not reach
 * this function — which is exactly why it logs when it does. A hit means the
 * client-side filter has a gap, and the log is how we find out rather than
 * assume. Matching is on the whole name only: `orange` sits inside `orange
 * juice`, `chicken` inside `rotisserie chicken`, and a substring rule would
 * confidently move both to the wrong aisle.
 */
function applyDirectory<T extends { normalizedName?: string; productName?: string; aisle: string; confidence: number; reasoning: string }>(
  results: T[],
  directory: Map<string, string>,
  storeId: string
): T[] {
  return results.map((r) => {
    const key = (r.normalizedName || r.productName || '').trim().toLowerCase();
    const placed = key ? directory.get(key) : undefined;
    if (!placed || placed === r.aisle) return r;
    logWarning('mapping.directoryOverride', { storeId, guessed: r.aisle, placed });
    return { ...r, aisle: placed, confidence: 1, reasoning: 'listed in the store directory' };
  });
}

/**
 * Main handler
 */
export const handler: AppSyncResolverHandler<Arguments, Response> = async (event) => {
  const callerHouseholds = requireHousehold(event);
  const startedAt = Date.now();

  const { storeId, productName, products } = event.arguments;

  // Validate: need storeId and either productName (single) or products array (batch)
  const isBatchMode = products && Array.isArray(products) && products.length > 0;
  const isSingleMode = !!productName;

  if (!storeId) {
    return {
      success: false,
      error: 'Missing required field: storeId',
    };
  }

  if (!isBatchMode && !isSingleMode) {
    return {
      success: false,
      error: 'Missing required fields: productName (single mode) or products array (batch mode)',
    };
  }

  try {
    // Fetch existing mappings for context

    // Deliberately serial. Running these together meant another household's
    // mappings — a list of what those people buy — were read before the
    // ownership check on the store could reject. Nothing reached the caller, but
    // it was read. One extra DynamoDB GET against an LLM call is free.
    const storeAisles = await fetchStoreAisles(storeId, callerHouseholds);
    const existingMappings = await fetchExistingMappings(storeId);

    // Only genuinely blocked when the store declares no aisles AND nothing has
    // ever been placed in it. A seeded store has seven departments, so this no
    // longer fires just because nobody has scanned a directory.
    if (existingMappings.length === 0 && storeAisles.length === 0) {
      return {
        success: false,
        error: 'This store has no aisles or departments set up yet.',
      };
    }



    // Build context for LLM
    const aisleContext = buildAisleContext(existingMappings, storeAisles);

    // The shape of every inference, content excluded. `contextChars` is here
    // because it is the input cost driver: a store with a rich layout builds a
    // longer prompt, and that is the difference between a cheap household and
    // an expensive one.
    const shape = {
      aisleCount: storeAisles.length,
      mappingCount: existingMappings.length,
      contextChars: aisleContext.length,
    };

    // Initialize Anthropic client
    const anthropic = new Anthropic({
      apiKey: ANTHROPIC_API_KEY,
    });

    // Never expected to change anything; see `applyDirectory`.
    const directory = signPlacements(existingMappings);

    // Check if batch mode
    if (isBatchMode) {
      const { results: batchResults, usage } = await inferAisleBatch(
        products!,
        aisleContext,
        anthropic
      );

      logEvent('ai.infer', {
        ...shape, ...tokenUsage(usage), mode: 'batch', model: MODEL,
        productCount: products!.length, resultCount: batchResults.length,
        outcome: 'ok', ms: Date.now() - startedAt,
      });

      // Map results to include normalizedName and productId from input
      const withNames = batchResults.map((r) => ({
        ...r,
        normalizedName: products!.find((p) => p.productName === r.productName)?.normalizedName || '',
      }));

      const resultsWithIds = applyDirectory(withNames, directory, storeId).map((r) => {
        const input = products!.find((p) => p.productName === r.productName);
        return {
          productName: r.productName,
          normalizedName: input?.normalizedName || '',
          productId: input?.productId,
          // Canonical id, not whatever spelling the model echoed back.
          suggestedAisle: canonicalAisleId(r.aisle, storeAisles),
          confidence: r.confidence,
          reasoning: r.reasoning,
        };
      });

      return {
        success: true,
        results: resultsWithIds,
      };
    }

    // Single mode (existing behavior)
    const raw = await inferAisle(productName!, aisleContext, anthropic);
    const [result] = applyDirectory(
      [{ productName: productName!, aisle: raw.aisle, confidence: raw.confidence, reasoning: raw.reasoning }],
      directory,
      storeId
    );

    logEvent('ai.infer', {
      ...shape, ...tokenUsage(raw.usage), mode: 'single', model: MODEL,
      productCount: 1, confidence: result.confidence,
      outcome: 'ok', ms: Date.now() - startedAt,
    });

    return {
      success: true,
      // Canonical id, not whatever spelling the model echoed back.
      suggestedAisle: canonicalAisleId(result.aisle, storeAisles),
      confidence: result.confidence,
      reasoning: result.reasoning,
    };
  } catch (error: any) {
    logFailure('ai.infer', error, {
      mode: isBatchMode ? 'batch' : 'single',
      productCount: isBatchMode ? products!.length : 1,
      ms: Date.now() - startedAt,
    });
    return {
      success: false,
      error: error.message || 'Unknown error occurred',
    };
  }
};
