import Foundation

/// The one call that ends a shopping trip, held on disk until it lands.
///
/// Ending a trip used to be about forty-one round trips — one per item moved to
/// suggestions, one per trip-scoped note, and one on the household. Offline that
/// failed in the worst possible shape: the item mutations queued happily, the
/// household mutation threw, and the shopper was left on the At Store screen
/// with items already moved and a trip the rest of the household could still see
/// running. Half finished, and no way to finish it.
///
/// Now the phone decides the whole outcome locally — it has to anyway, to show
/// the completion sheet — and one `finishShopping` mutation states it. This is
/// where that statement waits when there is no signal to send it on.
///
/// Held as a list, in order, rather than a single slot. A day with no signal can
/// hold two finished trips, and overwriting the first would leave its items sat
/// as ACTIVE on the server for ever — locally suggestions, remotely still on the
/// list, and the next refresh drags them back. Nothing is merged: each finish is
/// sent as it was written, and the server recognises a repeat by its `tripId`.
struct PendingFinish: Codable, Equatable {
    /// Generated by the phone that ended the trip, so the server recognises the
    /// same finish arriving twice. A lost reply looks exactly like a failure
    /// from here, so this will be re-sent, and applying it twice would drag a
    /// list somebody has since rebuilt back into suggestions.
    let tripId: String
    let householdId: String

    /// Items the server already knows about, going to suggestions.
    let toSuggestion: [String]

    /// Items whose trip-scoped note dies with the trip.
    let clearNotesFor: [String]

    /// Items added during the trip while offline. The server has never seen
    /// these, so they travel whole rather than as an id to update.
    let created: [CreatedItem]

    /// False when the trip was never announced — it started with no signal, so
    /// there is no household status to put back and nobody was ever told.
    let endTrip: Bool

    let queuedAt: Date

    struct CreatedItem: Codable, Equatable {
        let id: String
        let householdId: String
        let name: String
        let normalizedName: String
        let quantity: String?
        let notes: String?
        let notesEphemeral: Bool
        let isCustom: Bool
        let productId: String?
        let status: String
        let addedBy: String
        let addedAt: String
        let version: Int
    }
}

@MainActor
extension PendingFinish.CreatedItem {
    /// An item that was added offline during a trip and is now finished with.
    ///
    /// Status is hard-coded rather than copied: this only ever describes an item
    /// the trip has just put away, and the server writes exactly what it is
    /// given. `addedAt` goes out as the shape AppSync wants for `AWSDateTime`.
    init(finishing item: GroceryItem) {
        self.init(
            id: item.id,
            householdId: item.householdId,
            name: item.name,
            normalizedName: item.normalizedName,
            quantity: item.quantity,
            // The note died with the trip; do not resurrect it on the way up.
            notes: item.notesEphemeral ? nil : item.notes,
            notesEphemeral: false,
            isCustom: item.isCustom,
            productId: item.productId,
            status: "SUGGESTION",
            addedBy: item.addedBy,
            addedAt: AmplifyService.formatAWSDateTime(item.addedAt),
            version: item.version
        )
    }
}

@MainActor
enum PendingFinishStore {
    /// Tests point this at a temp directory, like the other stores here. Without
    /// it a test run would clobber whatever finish is waiting on the simulator.
    static var directoryOverride: URL?

    private static let filename = "pending-finish.json"

    static var fileURL: URL? {
        if let directoryOverride {
            return directoryOverride.appendingPathComponent(filename)
        }
        guard let dir = try? FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        ) else { return nil }
        return dir.appendingPathComponent(filename)
    }

    private static var encoder: JSONEncoder {
        let e = JSONEncoder()
        e.dateEncodingStrategy = .iso8601
        return e
    }

    private static var decoder: JSONDecoder {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .iso8601
        return d
    }

    static func load() -> [PendingFinish] {
        guard let url = fileURL, let data = try? Data(contentsOf: url) else { return [] }
        return (try? decoder.decode([PendingFinish].self, from: data)) ?? []
    }

    /// The oldest finish still waiting, or nil.
    static var next: PendingFinish? { load().first }

    static var isPending: Bool { !load().isEmpty }

    static func append(_ finish: PendingFinish) {
        write(load() + [finish])
    }

    /// Drop one that has landed, by trip. Never "remove the first" — a finish
    /// could have been appended while this one was in flight.
    static func remove(tripId: String) {
        write(load().filter { $0.tripId != tripId })
    }

    private static func write(_ finishes: [PendingFinish]) {
        guard let url = fileURL else { return }
        do {
            try encoder.encode(finishes).write(to: url, options: .atomic)
        } catch {
            // Nothing to do about it here, and the trip has already ended on
            // screen. Losing this means the household keeps a stale trip until
            // somebody clears it, which the abandoned-session path already
            // handles — worse than syncing, better than blocking the shopper.
            print("PendingFinishStore: could not save — \(error)")
        }
    }

    static func clear() {
        guard let url = fileURL else { return }
        try? FileManager.default.removeItem(at: url)
    }
}
